### ISSUE TITLE
use OpenBLAS develop branch

### ISSUE THREAD

**Issue by jeffhammond** [nv-legate/legate.numpy#25]
This is clearly an issue in OpenBLAS but it blocks my Legate Numpy install and is unexpected, based on my experience with OpenBLAS in other contexts.

```sh
jhammond@nuclear:~/LEGATE/np$ python3 ./install.py --install-dir $HOME/LEGATE --with-core $HOME/LEGATE 2>&1 | tee log
Verbose build is  off
Legate is installing OpenBLAS into a local directory...
Cloning into '/tmp/tmpm780ryjm'...
Note: switching to 'd2b11c47774b9216660e76e2fc67e87079f26fa1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Switched to a new branch 'master'
getarch_2nd.c: In function ‘main’:
getarch_2nd.c:14:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘SBGEMM_DEFAULT_UNROLL_M’?
   14 |     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   SBGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:14:35: note: each undeclared identifier is reported only once for each function it appears in
getarch_2nd.c:15:35: error: ‘SGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘SBGEMM_DEFAULT_UNROLL_N’?
   15 |     printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   SBGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:16:35: error: ‘DGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
   16 |     printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:17:35: error: ‘DGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘QGEMM_DEFAULT_UNROLL_N’?
   17 |     printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   QGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:21:35: error: ‘CGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
   21 |     printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:22:35: error: ‘CGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘QGEMM_DEFAULT_UNROLL_N’?
   22 |     printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   QGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:23:35: error: ‘ZGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
   23 |     printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:24:35: error: ‘ZGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘QGEMM_DEFAULT_UNROLL_N’?
   24 |     printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   QGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:71:50: error: ‘SGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SBGEMM_DEFAULT_Q’?
   71 |     printf("#define SLOCAL_BUFFER_SIZE\t%ld\n", (SGEMM_DEFAULT_Q * SGEMM_DEFAULT_UNROLL_N * 4 * 1 *  sizeof(float)));
      |                                                  ^~~~~~~~~~~~~~~
      |                                                  SBGEMM_DEFAULT_Q
getarch_2nd.c:72:50: error: ‘DGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SBGEMM_DEFAULT_Q’?
   72 |     printf("#define DLOCAL_BUFFER_SIZE\t%ld\n", (DGEMM_DEFAULT_Q * DGEMM_DEFAULT_UNROLL_N * 2 * 1 *  sizeof(double)));
      |                                                  ^~~~~~~~~~~~~~~
      |                                                  SBGEMM_DEFAULT_Q
getarch_2nd.c:73:50: error: ‘CGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SBGEMM_DEFAULT_Q’?
   73 |     printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 *  sizeof(float)));
      |                                                  ^~~~~~~~~~~~~~~
      |                                                  SBGEMM_DEFAULT_Q
getarch_2nd.c:74:50: error: ‘ZGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SBGEMM_DEFAULT_Q’?
   74 |     printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q * ZGEMM_DEFAULT_UNROLL_N * 2 * 2 *  sizeof(double)));
      |                                                  ^~~~~~~~~~~~~~~
      |                                                  SBGEMM_DEFAULT_Q
make: *** [Makefile.prebuild:74: getarch_2nd] Error 1
Makefile:154: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.
Traceback (most recent call last):
  File "./install.py", line 543, in <module>
    driver()
  File "./install.py", line 539, in driver
    install_legate_numpy(unknown=unknown, **vars(args))
  File "./install.py", line 359, in install_legate_numpy
    install_openblas(openblas_dir, thread_count, verbose)
  File "./install.py", line 143, in install_openblas
    execute_command(
  File "./install.py", line 62, in execute_command
    subprocess.check_call(args, cwd=cwd, shell=shell)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '8', 'USE_THREAD=1', 'NO_STATIC=1', 'USE_OPENMP=1', 'NUM_PARALLEL=32', 'LIBNAMESUFFIX=legate']' returned non-zero exit status 2.
```

**Comment by lightsighter** [comment]
Can you try building OpenBLAS independently of Legate and use the `--with-openblas` flag to point Legate at that after you've built it?

**Comment by lightsighter** [comment]
You can see the flags we're passing to OpenBLAS here:

```
make', '-j', '8', 'USE_THREAD=1', 'NO_STATIC=1', 'USE_OPENMP=1', 'NUM_PARALLEL=32', 'LIBNAMESUFFIX=legate'
```

**Comment by jeffhammond** [comment]
I "detected" my CPU and did `export TARGET=HASWELL` (it's Tiger Lake but AVX-512 client behaves closer to HASWELL than SKYLAKEX) and that resolved it.  I'll see if I can reproduce the OpenBLAS issue separately and deal with that in the appropriate manner.

**Comment by jeffhammond** [comment]
This is fixed in https://github.com/xianyi/OpenBLAS/tree/develop but not https://github.com/xianyi/OpenBLAS/tree/master or the specific hash Legate is using.  I recommend that Legate target the hash associated with `develop`.

**Comment by lightsighter** [comment]
Legate should be pointing at the 0.3.13 tag of OpenBLAS. Can you check if it is fixed in the 0.3.15 (most recent) tag? I'm inclined to keep us pointed at stable release versions of OpenBLAS.

**Comment by jeffhammond** [comment]
It appears to be fixed in 0.3.14 and later.

**Comment by lightsighter** [comment]
496c64d0c should bring us up to using v0.3.15

**Comment by jeffhammond** [comment]
re-testing legate numpy now.  will close when done.

**Comment by manopapad** [comment]
@marcinz I remember you were having some trouble with openblas v0.3.13, can you comment?

**Comment by jeffhammond** [comment]
I still can't get it to work without `TARGET=HASWELL` because of `getarch.c` problems that lead to `LIBCORE=(null)` and the `ar -ru ..` command failing.

I don't know how to fix this but it's easy enough for most people to work around by using a pre-built OpenBLAS or just exporting `TARGET`.  You could offer that diagnostic when the OpenBLAS build fails, but that's a feature not a bugfix.

**Comment by marcinz** [comment]
Open blas 0.3.14 had a known bug, and, prior to 0.3.15, the stable version was reverted to 0.3.15. So there were no specific issues except for the known bugs. We should be able to bump OpenBLAS to the latest version. I am not sure if we want to go with develop. I think that we should bump to 0.3.15 and then have a known issue with the fix that @jeffhammond provided (thank you).

**Comment by jeffhammond** [comment]
I think defaulting to a stable release makes sense, but perhaps you can add an option to use another version of OpenBLAS, not just an external build.  But I will try to solve this without user intervention today.

**Comment by marcinz** [comment]
Well, I think we could easily add a flag that takes OpenBLAS SHA and installs it from a commit. Is this what you are suggesting?

**Comment by jeffhammond** [comment]
Yeah, and detect special cases like `develop` as arguments to this option.
