### ISSUE TITLE
Using a scalar in `allclose` raises an `AttributeError`

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.numpy#27]
## Problem

Using a scalar in `allclose` raises `AttributeError: PROJ_1D_1D_`.

## To reproduce

1. step 1: create `test.py`
   ```python
   from legate import numpy as lnp
   import numpy as realnp

   # vanilla numpy works
   a = realnp.full(10, 1e-1)
   print(realnp.allclose(a, 1e-1))

   # legate numpy not working
   la = lnp.full(10, 1e-1)
   print(lnp.allclose(la, 1e-1))
   ```
2. step 2: run `test.py` with `legate --cpus 1 ./test.py -lg:numpy:test`

## Output
The first part that uses vanilla NumPy prints `True`.

The second part that uses Legate NumPy raises:
```
Traceback (most recent call last):
  File "<prefix>/lib/python3.8/site-packages/legion_top.py", line 408, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "<prefix>/lib/python3.8/site-packages/legion_top.py", line 200, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "./test.py", line 10, in <module>
    print(lnp.allclose(la, 1e-1))
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/module.py", line 459, in allclose
    return ndarray.perform_binary_reduction(
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/array.py", line 2068, in perform_binary_reduction
    dst._thunk.binary_reduction(
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/deferred.py", line 5167, in binary_reduction
    ) = self.runtime.compute_broadcast_transform(
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/runtime.py", line 2500, in compute_broadcast_transform
    self.first_proj_id + getattr(NumPyProjCode, proj_name),
  File "<prefix>/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: PROJ_1D_1D_
```

## Expected behavior

Working like vanilla NumPy, or raising an exception with a clear message of what is not supported.

**Comment by magnatelee** [comment]
Should be fixed by 8b85c00. @piyueh can you pull and try again?

**Comment by piyueh** [comment]
@magnatelee It's working now. But there's a minor difference in the outputs of vanilla NumPy and Legate NumPy. Vanilla NumPy returns a Python's native `bool`, while Legate NumPy returns a 1D boolean `ndarray` with shape `(1,)`. For example, the above example code returns:
```
True
[ True]
```
However, this is a minor issue for me.

I'll close the issue if you think this behavior (i.e., not returning a native `bool`) will not be changed soon.

**Comment by magnatelee** [comment]
I think I can fix it quickly, so let's keep this open.

**Comment by magnatelee** [comment]
Please pull and try again.

**Comment by piyueh** [comment]
@magnatelee Thanks! It's working. Closing the issue.

**Comment by piyueh** [comment]
@magnatelee I reopened this issue because if there's no `-lg:numpy:test` flag, the test failed. This is the error traceback

```
[0 - 7f77b186f000]    0.819757 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "<prefix>/lib/python3.8/site-packages/legion_top.py", line 408, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "<prefix>/lib/python3.8/site-packages/legion_top.py", line 200, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "./test.py", line 10, in <module>
    print(lnp.allclose(la, 1e-1))
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/module.py", line 459, in allclose
    return ndarray.perform_binary_reduction(
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/array.py", line 2068, in perform_binary_reduction
    dst._thunk.binary_reduction(
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/eager.py", line 947, in binary_reduction
    self.array[:] = np.allclose(
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```

**Comment by magnatelee** [comment]
Should be fixed now. Please pull and try again.

**Comment by piyueh** [comment]
Hi, I got this error:
```
[0 - 7f81bbd5c7c0]    0.742322 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "<prefix>/lib/python3.8/site-packages/legion_top.py", line 408, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "<prefix>/lib/python3.8/site-packages/legion_top.py", line 200, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "./test.py", line 10, in <module>
    print(lnp.allclose(la, 1e-1))
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/array.py", line 770, in __str__
    self._thunk.get_scalar_array(stacklevel=2), self.shape
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/eager.py", line 159, in get_scalar_array
    return self.array.reshape(())
AttributeError: 'bool' object has no attribute 'reshape'
```

**Comment by lightsighter** [comment]
Please pull and try again with febd3bf390f

**Comment by piyueh** [comment]
It wroks. Thanks! Closing the issue.
