### ISSUE TITLE
Undefined symbol: legion_auto_generate_id

### ISSUE THREAD

**Issue by K-Wu** [nv-legate/legate.numpy#7]
I installed legate.numpy on legate.core on my Ubuntu 18.04. After I manually exported LEGATE_MAX_DIMS and LEGATE_MAX_FIELDS to environment variables, I further got the following error when I import legate.numpy. Any idea how to fix this?
```
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import legate.numpy as np
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/legate/numpy/__init__.py", line 21, in <module>
    from legate.numpy import linalg, random
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/legate/numpy/linalg/__init__.py", line 19, in <module>
    from legate.numpy.linalg.linalg import *
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/legate/numpy/linalg/linalg.py", line 18, in <module>
    from legate.numpy.array import ndarray, runtime
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/legate/numpy/array.py", line 24, in <module>
    from legate.core import LegateArray
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/legate/core/__init__.py", line 19, in <module>
    from legate.core.legate import (
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/legate/core/legate.py", line 32, in <module>
    from legate.core.legion import (
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/legate/core/legion.py", line 858, in <module>
    class IndexPartition(object):
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/legate/core/legion.py", line 868, in IndexPartition
    part_id=legion.legion_auto_generate_id(),
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/home/kwu/anaconda3/envs/legate/lib/python3.8/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'legion_auto_generate_id' not found in library '<None>': python: undefined symbol: legion_auto_generate_id
```

**Comment by manopapad** [comment]
Legate.numpy won't work with the default python interpreter. You need to use the driver script from legate.core as explained here https://github.com/nv-legate/legate.core#how-do-i-use-legate, or the quickstart scripts at https://github.com/nv-legate/quickstart (the latter will save you some effort, assuming they can properly detect the available resources on your system).

The reason for this is that Legate is built on top of the Legion programming system, and at initialization time we expect to find the Legion runtime already set up and running. The driver script will launch Legion and instruct it to use your python script as the top-level task (i.e. the application entry point).

**Comment by K-Wu** [comment]
Got it. Thanks! It works now.
